
[ClassVersion("1.0.0.1"), FriendlyName("xEventLog")]
class MSFT_xEventLog : OMI_BaseResource
{
    [Key, Description("Name of the event log")] String LogName;
    [Write, Description("Specifies the names of the event log sources.")] String Source[];
};



